### ISSUE TITLE
development inside pull-request

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/sLapH-projection-NG#2]
@martin-ueding do you think it would be okay for you to perform development in a 'devel' branch with an open pull-request? That way, notifications are sent out for every commit, making it possible to follow development very easily (if one wants to do so).

**Comment by martin-ueding** [comment]
Sure, I'll try to make more meaningful commit messages from now on 😅.

The whole thing needs a few more iterations before I can start to compare results with Markus. Also the documentation needs a few more passes along the way.
