### ISSUE TITLE
GTPack Mathematica package

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/sLapH-projection-NG#4]
Would this be of any use?

https://www.frontiersin.org/articles/10.3389/fphy.2018.00086/full

**Comment by martin-ueding** [comment]
[A suggestion](https://mathematica.stackexchange.com/questions/188767/irreducible-representations-and-conjugacy-classes-for-the-octahedral-group?noredirect=1#comment525074_188767) was also to use https://www.gap-system.org/.

**Comment by martin-ueding** [comment]
I have mentioned these in the manual now.
